ekristen/aws-nuke

.gitignore
cmd/root.go

- Deprecate `--verbose` but it's still supported
- Expand logging to support all log levels provided by logrus
- Add .envrc and config.yaml to .gitignore

Logging Tweaks

---

.goreleaser.yml
Dockerfile.goreleaser

Adding GoReleaser makes it far easier for those who want to fork and build to do so. It also provides a more consistent build experience.

Add GoReleaser Support

---

.goreleaser.yml
Dockerfile.goreleaser

Statically build the binary so it works on all architectures by disabling CGO, not needed for this binary.

Statically Build

---

resources/macie2.go

This adds Macie to aws-nuke. Disabling Macie will remove all it's resources so there is no need to iterate over all the resources.

Add: Macie

---

resources/route53-resolver-rules.go

Fixes an issue where `domainName` can be nil, this guards against it.

fix: nil pointer

---

Dockerfile
README.md

- Fix the Dockerfile Entrypoint
- Update the README

update dockerfile entrypoint and readme

---

resources/memorydb-acl.go
resources/memorydb-cluster.go
resources/memorydb-parametergroups.go
resources/memorydb-subnetgroups.go
resources/memorydb-user.go

Adding 5 new resources from upstream aws-nuke. These changes were cherry-picked into this branch, then converted to the libnuke format that ekristen/aws-nuke@v3 uses.
- memorydb-acl.go
- memorydb-cluster.go
- memorydb-parametergroups.go
- memorydb-subnetgroups.go
- memorydb-user.go

add(resources): MemoryDB from upstream

---

resources/cloudfront-key-groups.go
resources/cloudfront-origin-request-policy.go
resources/cloudfront-public-keys.go

this adds the following resources and converts them to the libnuke format
- cloudfront-key-groups
- cloudfront-origin-request-policy
- cloudfront-public-keys

 add new cloudfront resources from upstream converted to libnuke format

---

resources/elasticache-subnetgroups.go
resources/elasticache-usergroups.go
resources/elasticache-users.go

This adds the following resources from the upstream project and converted to the libnuke format. It also pulls in a change to the filter for the elasticache-subnetgroups
- elasticache-users
- elasticache-usergroups

 add new elasticache resources from upstream converted to libnuke format

---

pkg/awsutil/session.go
pkg/commands/nuke/command.go

This brings back all the existing cli options, but adds environment variables to have parity with the upstream tool.
Additionally this allows for external id and role session name to be set which is an upstream ask https://github.com/rebuy-de/aws-nuke/issues/817
Resolves #61

feat(aws-auth): finish parity with upstream

---

docs/cli-experimental.md
docs/cli-options.md
docs/cli-usage.md
docs/features/bypass-alias-check.md
docs/standards.md
mkdocs.yml
pkg/commands/nuke/command.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/testdata/bypass-alias.yaml
pkg/config/testdata/deprecated-feature-flags.yaml
pkg/config/testdata/incomplete.yaml
pkg/config/testdata/invalid.yaml

This allows the bypass of the AWS alias check code.
See the full documentation on how to bypass, but it's essentially a two step process, one of which only has to be done once.
You must list the account in the configuration under `bypass-alias-check-accounts` and then present the CLI flag (or it's equivalent environment variable)
Resolves #62

feat: allow bypass of aws alias checks

---

docs/cli-examples.md
mkdocs.yml

Upstream users have requested CLI usage examples. This introduces 3, including one specifically for force 
https://github.com/rebuy-de/aws-nuke/issues/668

docs: add cli examples, including for --force usage

---

pkg/commands/nuke/command.go

Been fixed in the upstream libnuke lib but need to upgrade to that, for now this is quick fix to get a default run loop sleep back in place. It was instance, now after looping through resources it'll sleep for 5 before looping again. This matters less with dozens or hundreds of resources but if you are deleting a singular resource type, this can cause a lot of extra calls to the AWS APIs for no reason.

fix: quick fix for default run sleep

---

pkg/awsutil/account.go

This fixes a bug with the `no-alias-check` flag and there being aliases on the account.

fix: bug with no alias check

---

docs/auth.md
pkg/awsutil/session.go
pkg/commands/nuke/command.go

Updates the aws authentication documentation, adds the `-c` option back for `--config` and fixes a bug where session and role name were not being treated as optional.
- Resolves #78 
- Resolves #79

fix: bug with external id and session name, missing -c option and docs

---

go.mod
go.sum

The original aws-nuke logged the error with a custom property not being supported, this updates to libuke@0.10.1 that fixes this bug.
Resolves #81

fix: log error as warning vs throwing error with property not supported

---

docs/cli-options.md
docs/cli-usage.md
main.go
mkdocs.yml
pkg/awsutil/account.go
pkg/commands/account/account.go
pkg/commands/config/config.go
pkg/commands/nuke/command.go

This adds two new commands to help with debugging and informational purposes for users. 
- `explain-account` will show what account you are authenticated against and how
- `explain-config` will show the rendered configuration for the account you are authenticated against or the account specified on the cli

feat: new explain commands for debugging and informational purposes

---

tools/migrate-resource/main.go

Update the migrate tool to have the correct imports.

chore: fix migrate tool default imports

---

docs/cli-usage.md
pkg/commands/config/config.go

- Fixes a bug with the explain-config command around account id determination.
- Adds a few more bits of information to the output
- Updates the CLI usage documentation to match

fix: explain config command

---

resources/ecr-public-repository.go

This fixes a bug where ECRPublicRepository was being queried in all regions when it is only supported in `us-east-1`.

fix(resource/ecrpublicrepository): only run if region is us-east-1

---

resources/iam-rolesanywhere-crls.go
resources/iam-rolesanywhere-profiles.go
resources/iam-rolesanywhere-trust-anchors.go

Cherry picks IAM Roles Anywhere from @rburchill commit and modify to libnuke format.
reference: https://github.com/rebuy-de/aws-nuke/pull/1186

feat: add IAM Roles Anywhere CRLs, Trust Anchors, and Profiles

---

docs/features/enabled-regions.md
docs/features/global-filters.md
docs/features/signed-binaries.md
docs/index.md
mkdocs.yml
tools/compare-resources/main.go
tools/migrate-resource/main.go

improving docs and fixing some issues with internal tooling

chore: update docs and internal tooling

---

pkg/commands/nuke/nuke.go

- Renames the file for the `nuke` command to `nuke.go` in line with the name of the other command files
- Adds the `-q` alias for the `--quiet` switch on the `nuke` command, as this was present in the original `aws-nuke` and is also a pretty universal alias

feat: rename command file to nuke and add q alias for --quiet

---

docs/installation.md

Running the build command as currently stated in the docs results in the following error (on my machine):
```bash
(main)> goreleaser --clean --snapshot --single-target
⨯ command failed                                   error=unknown flag: --single-target
```
Adding the `build` command before `--clean` results in the intended behavior.

docs: add missing build command

---

resources/cloudfront-response-headers-policies.go

Implements the upstream implementation of this, formatted for libnuke, keeping original author commit attribution. https://github.com/rebuy-de/aws-nuke/pull/1140

feat: cloudfront response headers policy

---

resources/iot-thinggroups.go

Attempts to fix deleting dynamic thing groups which was brought up https://github.com/rebuy-de/aws-nuke/issues/1199.
Creating dynamic thing groups are bit more complicated so this is tough to test.

fix(iot-thinggroups): support deleting dynamic thing groups

---

resources/cloudfront-cache-policy.go

This adds the cloudfront cache policy by way of [cherry picked commit](https://github.com/MikeSchouw/aws-nuke/commit/dd2be49755ece7ac993a0c1fe7d1c6ad68d721ad) from @MikeSchouw and their upstream branch based on this PR https://github.com/rebuy-de/aws-nuke/pull/1152
Rebased the original commit to turn the commit into semantic commit message format, but preserve Mike's contributions as much as possible. Converted to the libnuke resource format and add a nolint statement for golangci-lint to ignore.
Resolves #135 
- https://github.com/rebuy-de/aws-nuke/issues/1151
- https://github.com/rebuy-de/aws-nuke/pull/1152

feat: add cloudfront cache policy resource

---

pkg/commands/account/account.go
pkg/commands/nuke/nuke.go

Refactors code to allow for all regions to be supported for the `AWS_DEFAULT_REGION` environment variable by doing a lookup to determine it's proper partition. It also happens to simplify the code as well.
Resolves #142

fix(awsutil): properly determine partition for all supported regions

---

resources/sagemaker-apps.go
resources/sagemaker-spaces.go

Closes #157 
This PR is a port of https://github.com/rebuy-de/aws-nuke/pull/1197
**Output with feature activated**
```
> aws-nuke - 3.0.0-dev - dirty
Do you really want to nuke the account with the ID 000000000000 and the alias 'test-account'?
Do you want to continue? Enter account alias to continue.
> test-account
eu-west-1 - SageMakerApp - default - [AppName: "default", AppType: "JupyterServer", DomainID: "d-fafofydwvicv", SpaceName: "test"] - would remove
eu-west-1 - SageMakerSpace - test - [DomainID: "d-fafofydwvicv", LastModifiedTime: "2024-05-03 10:31:30.218 +0000 UTC", SpaceName: "test", Status: "InService"] - would remove
eu-west-1 - SageMakerDomain - d-fafofydwvicv - [CreationTime: "2024-05-03T10:25:08Z", DomainID: "d-fafofydwvicv"] - would remove
eu-west-1 - …
```

feat(sagemaker-spaces): add support for Sagemaker Spaces

---

resources/configservice-configrules.go

Conformance packs add config rules. These cannot be deleted. This excludes those rules from trying to be removed.

fix(configservice-configrules): filter out rules created by config-conforms

---

resources/cloudformation-stack.go
resources/configservice-conformance-pack.go

This adds support for removing config conformance packs via the config service. It also filters out cloudformation stacks that are managed by the config conformance packs because they cannot be removed. The conformance pack has to be removed, which in turn removes the stack.

feat: support config conformance pack removal

---

resources/cloudformation-stack.go

A recent change to filter out AWS managed cloudformation stacks that cannot be removed successfully was added. However the description field can sometimes be a nil pointer and it wasn't protected against that. This fixes that bug.
Resolves #183

fix(cloudformation-stack): protect against nil pointer

---

resources/ec2-image.go

This improves the EC2Image resource by introducing 3 new settings, by default these settings are false because they would change the behavior of the EC2Image discovery.
In Version 4, these settings will be enabled by default.
- IncludeDisabled
- IncludeDeprecated
- DisableDeregistrationProtection
There are 2 types of protection, one with a 24 hour cool-down, and 1 without a cool-down. If the image is protected by the option without a cooldown, the image will be removed immediately given that the `DisableDeregistrationProtection` setting is true. 
If the image is protected with the 24 hour cool-down and `DisableDeregistrationProtection` is true, then aws-nuke will disable the deregistration protection and then filter the resource out due to it not being eligible for removal. You will then …

feat(ec2-image): include disabled and deprecated images

---

go.mod
go.sum
resources/cloudformation-stack.go
resources/ec2-image.go
resources/ec2-instance.go
resources/elbv2-alb.go
resources/lightsail-instances.go
resources/qldb-ledger.go
resources/quicksight-subscriptions.go
resources/rds-instances.go

This addresses an issue where if a setting isn't set, it can cause an nil pointer the way the setting pkg was written. A quick fix and release of https://github.com/ekristen/libnuke/releases/tag/v0.17.1 to add type returning functions avoids the nil pointer issue. 
The rest of this PR is updating the setting calls to use the new `GetBool` vs `Get` to remove the possibility of nil pointer, this will specifically address the nil pointer that occurred in issue #199 with respect to EC2Image
Resolves #199

fix: nil pointer error with settings

---

pkg/commands/nuke/nuke.go

Config logger ensures that logs during config loading get printed.
https://github.com/ekristen/aws-nuke/pull/198 added logger to `Nuke`. This adds logger early when loading the config to `Config`.
This is related to the scenario mentioned in https://github.com/ekristen/libnuke/issues/61#issuecomment-2181633826.
Before:
```console
$ ./aws-nuke run -c nuke-cfg.yaml
> aws-nuke - 3.0.0-dev - dirty
Do you really want to nuke the account with the ID XXXXX and the alias 'xxxxx'?
Do you want to continue? Enter account alias to continue.
```
After:
```console
$ ./aws-nuke run -c nuke-cfg.yaml
WARN[0000] deprecated configuration key 'account-blacklist' - please use 'blocklist' instead  component=config
WARN[0000] deprecated resource type 'EKSNodegroups' - converting to 'EKSNodegroup' …
```

fix: set config logger

---

CONTRIBUTING.md

Fix the Go import indentations in the example code snippet of the CONTRIBUTING doc.

docs: fix go import indentations in example

---

pkg/testsuite/logrus.go
resources/elasticache-memcacheclusters.go
resources/elasticache-memcacheclusters_mock_test.go
resources/elasticache-subnetgroups.go
resources/elasticache-subnetgroups_mock_test.go

Fixes a bug where the cluster id was incorrectly being used in place of the arn to lookup tag data for the resources.
Resolves #208

fix: elasticache resources using cluster id vs arn for tag lookup

---

resources/rds-snapshots.go

Unsure the circumstances but it appears that the `SnapshotCreateTime` can sometimes be `nil` therefore we need a guard for it.
Resolves #221

fix(rds-snapshot): protect against nil pointer

---

resources/ecs-task.go
resources/ecs-task_mock_test.go

Adds tags to the `ECSTask` and renames the files to their singular version to align with the newer standard.
Resolves #226

feat(ecs-task): support resource tags

---

resources/iot-authorizers.go

You have to first set IoT authorizers to inactive before deleting.
Addresses https://github.com/rebuy-de/aws-nuke/issues/1251 in this version of aws-nuke

fix(iot-authorizer): set to inactive before removing

---

resources/elastictranscoder-preset.go

- Adds `elastictranscoder-preset` resource,  thanks @swhite-oreilly 
- Converts to [libnuke](https://github.com/ekristen/libnuke) format
- Implements upstream https://github.com/rebuy-de/aws-nuke/pull/1255

feat: elastictranscoder preset support

---

pkg/awsmod/batch.go
resources/iam-user_test.go
resources/s3-bucket.go
resources/s3-bucket_test.go
resources/s3-buckets.go

This adds the ability to bypass the governance retention on s3 objects in a bucket and still clean the bucket up.
This adds a new setting to the `S3Bucket` called `BypassGovernanceRetention`, when set to true, the recursive delete of a bucket will set `BypassGovernanceRentention` to true when calling to S3, thus allowing the bypass of any governance enforcement.
**Note:** if you are using COMPLIANCE mode this will not work. aws-nuke will also currently fail if any objects are in compliance mode.

feat: s3 bucket - bypass governance retention

---

resources/elasticache-users.go

There can be multiple ElastiCache users with `name` of "default", but only one with `ID` of "default", which cannot be deleted.

fix(elasticache): use ID instead of name for default user filter

---

resources/configservice-configrule.go
resources/configservice-configrules.go

If you attempt to delete a config rule that has a remediation config it will fail, this fixes it so that if a remediation config is present it deletes that first.

feat(configservice-configrule): remove remediation config

---

resources/iam-virtual-mfa-device.go
resources/iam-virtual-mfa-device_mock_test.go

It's possible to have MFA devices that are not assigned to a user, this fixes it so that those devices can be deleted

fix(iam-virtual-mfa-device): handle unassigned mfa devices

---

pkg/commands/nuke/nuke.go

This adds a CLI flag to the run command to allow the user to change the run loop sleep delay.
Resolves #257

feat(run): add flag to control the run loop sleep delay

---

pkg/awsutil/consts.go
resources/ec2-vpc-endpoint-connection.go

This fixes a bug where ec2 vpc endpoint connections can remain in the describe API in the rejected state. The rejected state is a form of deletion, therefore we need to filter it once it hits this state.
Upstream issue is https://github.com/rebuy-de/aws-nuke/issues/1258
Resolves https://github.com/ekristen/aws-nuke/issues/272

fix(ec2-vpc-endpoint-connection): filter rejected state

---

docs/config.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/testdata/no-blocklist-term-prod.yaml

- This adds support for expanding the list of terms that will be used to block aliases.
- This also adds support for **REMOVING** the default blocklist terms like `prod` from the alias checks.
**Note:** if you use the Bypass Alias Check, this feature has no affect, as all alias checking is disabled.

feat(config): custom alias keyword blocklist and disable default keywords

---

resources/quicksight-user.go
resources/quicksight-users.go

When I tested this on my account I found it to be more reliable to delete via `PrincipalId` vs `UserName` as it was possible to have users without a `UserName`.

feat(quicksight): support deleting quicksight users

---

docs/resources/iam-role.md
mkdocs.yml
resources/apigateway-api-key.go
resources/apigateway-usage-plan.go
resources/cloudwatchevents-rule.go
resources/databasemigrationservice-certificate.go
resources/databasemigrationservice-certificates.go
resources/eks-fargate-profile.go
resources/eks-fargate-profile_mock_test.go
resources/iam-role-policy.go
resources/iam-role.go
resources/iam-role_mock_test.go
resources/mgn-source-server.go

- https://github.com/rebuy-de/aws-nuke/pull/1164
- https://github.com/rebuy-de/aws-nuke/pull/1104
- https://github.com/rebuy-de/aws-nuke/issues/1124
- https://github.com/rebuy-de/aws-nuke/pull/1172

feat: general improvements

---

docs/config-contrib.md
docs/resources/ec2-image.md
docs/resources/iam-role.md
docs/resources/overview.md
docs/resources/s3-bucket.md
docs/resources/s3-object.md
mkdocs.yml
resources/apigateway-api-key.go
resources/apigateway-restapis.go
resources/ec2-eip.go
resources/kms-key.go
resources/kms-key_mock_test.go
resources/neptune-instance.go
resources/neptune-instances.go
resources/opensearchservice-pipeline.go
resources/secretsmanager-secret.go

Improvements to the documentation around EC2Image and S3Object resource types. Additionally implements rate limiting fixes for API Gateway Rest API and API Key, both of which can only delete 1 resource per 30 seconds. 
- Fixes a bug with `NeptuneInstance` returning non-neptune engine RDS instances.
- Adds new `OSPipeline` resource
- Fixes issue where AWS managed secrets weren't being excluded
- Adds first KMS Alias to KMS Key as property `Alias` for filtering purposes
- Resolves #374 
- Resolves #371
- Resolves #301
- Resolves #132
- Resolves #330
- Resolves #133
- Resolves #334 
- Resolves #367

feat: various fixes and features - october

---

docs/cli-experimental.md
docs/config-filtering.md
docs/features/filter-groups.md
go.mod
go.sum
mkdocs.yml
pkg/commands/nuke/nuke.go

By default all filters are part of group `default`, this allows you to set `group: <value>` for any filter. 
Filters within the same group are `OR`, meaning if any are true, then the resource is filtered.
If more than 1 filter group is present, they are `AND`ed together and both groups must be true for the filter to match.
This is the filter definition
```yaml
filters:
IAMUser:
- value: "testing"
type: contains
group: group1
- property: tag:test
value: "alpha"
group: group2
```
**WITHOUT** filter groups, both resources get filtered because they match 1 or more filters.
```console
global - IAMUser - testing - [CreateDate: "2024-10-15T22:42:39Z", Name: "testing", Path: "/", UserID: "AIDAZI2LHXQ5T2ABOSX2H"] - filtered by config
global - IAMUser - testing12345 - [CreateDate: …
```

feat(experimental): filter groups

---

resources/ec2-vpc-endpoint-connection.go

* Adds `tags` support for `EC2VPCEndpointConnection` resource
* I see some resources in the repo use `tags` and others use `Tags` for the variable naming. I have picked `tags` as that seems more prevalent

feat(ec2-vpc-endpoint-connection): add tags to properties

---

go.mod
go.sum

This was a bug that was accidentally introduced while working on the filter group feature for aws-nuke in underlying library the powers the tool, libnuke.
This has been fixed in v0.21.1 of libnuke and this returns the error to a warning.
Resolves #392

fix(dep): update github.com/ekristen/libnuke to v0.21.1

---

resources/kms-key.go
resources/kms-key_mock_test.go

Filter custom KMS keys in `PendingReplicaDeletion` as they've already been scheduled for deletion.
Closes #408

fix(kms-key): filter pending replica deletion state

---

resources/iotsitewise-access-policy.go
resources/iotsitewise-asset-model.go
resources/iotsitewise-asset.go
resources/iotsitewise-dashboard.go
resources/iotsitewise-gateway.go
resources/iotsitewise-portal.go
resources/iotsitewise-project.go

feat(iotsitewise): add portal, project, gateway, dashboard, asset, asset model and access policy

---

CONTRIBUTING.md
docs/contributing.md
docs/resources.md

This is a minor change on documentation files.
While setting up a new environment I realized [docs/resources.md](docs/resources.md) was out of date with reference to `github.com/ekristen/aws-nuke/pkg/nuke` instead of `github.com/ekristen/aws-nuke/v3/pkg/nuke`
I changed also in [CONTRIBUTING.md](CONTRIBUTING.md) to have a clean import example. It is probaby not a real world problem mostly because the documentation tells to use `tools/create-resource/main.go` but just for cleanup 😄

docs: fix usage of libnuke and aws-nuke/v3 in examples

---

pkg/awsutil/session.go
resources/iottwinmaker-component-type.go
resources/iottwinmaker-entity.go
resources/iottwinmaker-scene.go
resources/iottwinmaker-sync-job.go
resources/iottwinmaker-workspace.go

Closes #421 
**IMPORTANT**: To have the feature working, I had to give the endpoint in aws-nuke configuration. I guess it is the logic in pkg/awsutil/session.go not supporting the particular IoT TwinMaker endpoints. IoT TwinMaker have two endpoints:
- api.iottwinmaker.us-west-1.amazonaws.com
- data.iottwinmaker.us-west-1.amazonaws.com
The configuration to add to test this feature is:
```
endpoints:
- region: eu-west-1
services:
- service: iottwinmaker
url: iottwinmaker.eu-west-1.amazonaws.com
```

feat(iottwinmaker): add workspace, component type, entity, scene, syncjob

---

resources/bedrock-evaluation-jobs.go
resources/bedrock-guardrails.go

Similar to #161 but requires upgrading AWS SDK version.

feat(bedrock): add guardrails and evaluation jobs

---

resources/bedrock-custom-models.go
resources/bedrock-model-customization-jobs.go
resources/bedrock-model-invocation-logging-configuration.go
resources/bedrock-provisioned-model-throughputs.go

feat(bedrock): add bedrock custom models, customization jobs, provisioned throughput and logging configuration

---

resources/bedrock-agent-datasource.go

fix(bedrockagent): set Bedrock Datasource data deletion policy to RETAIN before deleting it

---

resources/codeguru-profiling-group.go

PR to add new resource to support CodeGuru Profiler [profiling groups](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/working-with-profiling-groups.html), can rename to match convention if its missing `Profiler` from name (`CodeGuruProfilerProfilingGroup`?).
Tested scan
> aws-nuke - 3.0.0-dev - dirty
Do you really want to nuke the account with the ID [XXX] and the alias '[XXX]'?
Do you want to continue? Enter account alias to continue.
>  \> [XXX]<br>
eu-west-2 - CodeGuruProfilingGroup - [ComputePlatform: "Default", Name: "default-one"] - would remove
eu-west-2 - CodeGuruProfilingGroup - [ComputePlatform: "Default", Name: "default-two"] - would remove
eu-west-2 - CodeGuruProfilingGroup - [ComputePlatform: "AWSLambda", Name: "lambda-one"] - would remove
eu-west-2 - …

feat(resource): add code guru profiler profiling group resource

---

go.sum
resources/opensearchserverless-collections.go

This PR introduces support for managing OpenSearch serverless collections. It allows deletion of collections based on three properties: ID, ARN, and NAME.
I have tested this feature by running AWS Nuke on an AWS account containing four collections. The tool successfully removed the specified collections based on the provided filters.
This PR fixes #344

feat(resource): support for opensearch serverless collections

---

docs/resources/kms-alias.md
resources/kms-alias.go
resources/route53-resource-record.go
resources/route53-resource-record_test.go

This passes the tags from the KMS Key to the KMS Alias as well as the Route53 Zone to the Route53 Record Set.
Each are prefixed by `key:tag:` and `zone:tag` respectively.
- Resolves #457 
- Resolves #297

feat: pass tags to related resources for kms and route53

---

docs/features/name-expansion.md
docs/features/overview.md
docs/index.md
mkdocs.yml
pkg/commands/list/list.go
pkg/commands/nuke/nuke.go

This allows for the expansion of resource names using glob patterns supported by https://pkg.go.dev/github.com/mb0/glob?utm_source=godoc
At a basic level `*` is supported. You can now include and exclude using glob patterns. 
> [!IMPORTANT]  
> This feature is **NOT** currently supported for filters. You will need to continue to name resources types by their full name OR use the [Global Filters](https://aws-nuke.ekristen.dev/features/global-filters/) feature.
Please see the documentation included in this PR for more information on it's scope and usage. 
For example `OpsWorks*` will expand to now match the following resources:
```
OpsWorksApp                                            
OpsWorksCMBackup                                       
OpsWorksCMServer …
```

feat: expand resource names

---

docs/resources/cloud-watch-logs-log-group.md
resources/cloudwatchlogs-loggroup.go
resources/cloudwatchlogs-loggroup_test.go
resources/cloudwatchlogs-loggroups.go

feat: add new property to CloudWatchLogsLogGroup

---

resources/cloudcontrol.go
resources/cloudcontrol_test.go

Introducing rate limiting to cloud control api resources. It is a global rate limit for cloud control so all resources leverage it that are cloud control based. This introduces a global rate limit of 25 req/sec to all cloud control describe resource calls.
https://github.com/ekristen/aws-nuke/actions/runs/12755642492
- Resolves #508

feat(cloudcontrol): implement rate limit w/ better logging

---

resources/ecs-clusters.go

This PR adds the missing `Include` parameter to also return the tags associated with ECS clusters, see the [official AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeClusters.html#API_DescribeClusters_RequestSyntax).

feat(ecs-clusters): return cluster tags properly #306

---

resources/rds-instances.go

Fixes #347 
To make use of this fix, the `StartClusterToDelete` setting needs to be enabled (which will start the cluster before deleting the instance):
```yaml
settings:
RDSInstance:
StartClusterToDelete: true
```

fix(rds-instances): handle stopped clusters

---

resources/ecs-services.go

This fixes a bug in the pagination handling for `ECSService`, which caused some ECS services to not get discovered if a cluster contains more than 10 of them.
Fixes #578

fix(ecs-services): fix pagination

---

resources/iam-open-id-connect-provider.go

When running `aws-nuke` with a user that lacks permissions to retrieve details about a specific `OpenIDConnectProvider`, the tool currently skips all `OpenIDConnectProvider` resources. This fix ensures that `aws-nuke` logs the error but continues processing, aligning its behavior with how other resources are handled.

fix(OpenIDConnectProvider): inaccessible providers

---

resources/accessanalyzer-analyzer.go

Previously this wasn't detecting all analyzers, now it will, but will filter out org level as they are usually not accessible for deletion.

fix(access-analyzer): scan all types, filter org level

---

resources/backup-vaults-access-policies.go

Fixes https://github.com/ekristen/aws-nuke/issues/604
Using the same setup documented in #604 , I ran the module and the Vault Policy was updated and deleted as expected:
```
aws-nuke - 3.0.0-dev - dirty
no-prompt flag set, continuing without prompting user
waiting 3s before continuing
starting scan for resources
us-east-1 - AWSBackupVaultAccessPolicy - aws/efs/automatic-backup-vault - [] - would remove
Scan complete: 1 total, 1 nukeable, 0 filtered.
no-prompt flag set, continuing without prompting user
waiting 3s before continuing
us-east-1 - AWSBackupVaultAccessPolicy - aws/efs/automatic-backup-vault - [] - triggered remove
Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished
us-east-1 - AWSBackupVaultAccessPolicy - aws/efs/automatic-backup-vault - [] - waiting for removal …
```

fix(backup-vaults-access-policies): Allow cross-account assumed roles to delete Backup Vault Policies

---

go.mod
go.sum
pkg/commands/nuke/nuke.go

Introduces two new CLI flags that are configurable via environment variables. These flags are **hidden** by default.
- `--parallel-queries` - `AWS_NUKE_PARALLEL_QUERIES` (default: 16)
- `--max-queue-size` - `AWS_NUKE_MAX_QUEUE_SIZE` (default: 50k)
https://github.com/ekristen/aws-nuke/actions/runs/13981419114

feat(cmd/nuke): allow config and override of max queue size

---

resources/waf-rules.go
resources/wafregional-rule-predicates.go
resources/wafregional-rules.go

Fixes below runtime error when removing `WAFRegionalRule` resources due to nil `rule` field. Caused by lack of error checking on `GetRule` function, which was failing due to throttling. I've added error checking and rate limiting.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5f12e07]
goroutine 1 [running]:
main.main.func1()
github.com/ekristen/aws-nuke/v3/main.go:28 +0x54
panic({0x70f5640?, 0xd81b2c0?})
runtime/panic.go:787 +0x132
github.com/ekristen/aws-nuke/v3/resources.(*WAFRegionalRule).Remove(0xc001422600, {0x7940334e2d7df14?, 0xc000d2e580?})
github.com/ekristen/aws-nuke/v3/resources/wafregional-rules.go:82 …
```

fix(waf-rules): runtime error due to throttling

---

docs/config-custom-endpoints.md
docs/config-filtering.md
docs/quick-start.md

There are lots of lingering docs around where it's referencing `account-blocklist`, but it is using `blocklist` now?

docs: update to use blocklist instead of account-blocklist

---

resources/iam-role.go
resources/iam-role_mock_test.go

In order to delete a ServiceLinkedRole, the API [DeleteServiceLinkedRole](https://docs.aws.amazon.com/IAM/latest/APIReference/API_DeleteServiceLinkedRole.html) should be used. This returns an identifier which can then be used to poll the API [GetServiceLinkedRoleDeletionStatus](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetServiceLinkedRoleDeletionStatus.html). This additional business logic is forked using the same methodology as the existing `Filter()`, however, it does not check for the setting a second time as that must be true to have reached this stage.
There are two `sleep` calls in the PR, one to delay post the initial deletion request which seems to take time to propagate. The second is to delay slightly during polling.

feat: Fully support the deletion of IAM ServiceLinkedRoles

---

pkg/commands/global/global.go

Add an option to force coloring of logging output. 
Resolves #645

feat(logging): add option to force coloring

---

resources/opensearchserverless-collections.go

fix: missing string function causing oscollection to print out incorrectly to the screen:
without string()
with string()

fix(resource:OSCollection): added missing string function to opensearchserverless-collections.go

---

pkg/awsmod/batch.go
resources/s3-bucket.go
resources/s3-bucket_test.go

S3 has a maximum batch deletion for S3Objects of 1000. When clearing buckets with large quantities of S3Objects, a larger batch size improves speeds. In personal testing I've found that using a 1000 count batch size has improved the deletion of a S3 bucket containing 50,000 objects was reduced from about 8min to 2min.
This change makes the batch size for S3Object deletion configurable

feat: Add configurable S3Object deletion batch size

---

resources/cloudformation-stack.go

This is a bug fix to address an issue where TerminationProtection is not disabled on CF stacks in the region `ap-southeast-3`. This was traced back to the error message received from CloudFormation where it does not wrap brackets around the stack name. This fix is accomplished via a less-strict, but still reasonably so, conditional for the expected error message.
```
AWS Nuke: time="2025-06-18T22:21:50Z" level=error msg="CloudFormationStack stackName=Test attempt=0 maxAttempts=3 delete failed: ValidationError: Stack Test cannot be deleted while TerminationProtection is enabled\n\tstatus code: 400, request id: 2f3ebe96-358d-4ec3-bae7-88f5954b1dc8" component=scanner region=ap-southeast-3 resource=FSxFileSystem
```
I do not have explanation for the difference in the error message across …

fix(cloudformation): improve termination protection message matching

---

docs/resources/bedrock-agent-alias.md
docs/resources/bedrock-flow-alias.md
docs/resources/iam-user.md
docs/resources/mgn-application.md
docs/resources/mgn-job.md
docs/resources/mgn-launch-configuration-template.md
docs/resources/mgn-replication-configuration-template.md
docs/resources/mgn-source-server.md
docs/resources/network-firewall-logging-configuration.md
docs/resources/network-firewall-policy.md
docs/resources/network-firewall-rule-group.md
docs/resources/network-firewall.md
mkdocs.yml
resources/iam-user.go
resources/iam-user_mock_test.go

This adds a setting to the `IAMUser` that allows for bypassing the removal the permission boundary. User @npellegrin has pointed out that they have a SCP that prevents removing of boundaries and the AWS API does not require the removal of the permission boundary before the user, therefore to keep existing flow in place, but allow use of tool by others that have more restrictions.
Resolves https://github.com/ekristen/aws-nuke/issues/715

fix(iam-user): allow bypass permission boundary removal
