ekristen/aws-nuke

.github/workflows/docs.yaml
.github/workflows/release.yml
.github/workflows/tests.yml

Updating a bunch of actions to take care of PRs that renovate would like to open up.

update github workflow action versions

---

resources/appconfig-applications.go
resources/appconfig-configurationprofiles.go
resources/appconfig-deploymentstrategies.go
resources/appconfig-environments.go
resources/appconfig-hostedconfigurationversions.go

this adds 5 new resource types and converts them to libnuke format
- appconfig-applications
- appconfig-configurationprofiles
- appconfig-deploymentstrategies
- appconfig-environments
- appconfig-hostedconfigurationversions

add appconfig resources from upstream

---

resources/memorydb-acl.go
resources/memorydb-cluster.go
resources/memorydb-parametergroups.go
resources/memorydb-subnetgroups.go
resources/memorydb-user.go

had to redo the pull request after reverting the previous due to accidental squash merge, to keep commit history from original contributors need to do a standard merge

add memorydb resources from upstream converted to libnuke format

---

resources/appconfig-applications.go
resources/appconfig-configurationprofiles.go
resources/appconfig-deploymentstrategies.go
resources/appconfig-environments.go
resources/appconfig-hostedconfigurationversions.go

had to redo the pull request after reverting the previous due to accidental squash merge, to keep commit history from original contributors need to do a standard merge

add appconfig resources from upstream converted to libnuke format

---

resources/apprunner-connection.go
resources/apprunner-service.go

had to redo the pull request after reverting the previous due to accidental squash merge, to keep commit history from original contributors need to do a standard merge

add apprunner resources from upstream converted to libnuke format

---

resources/opensearchservice-packages.go
resources/opensearchservice-vpcendpoints.go

this adds the following resources from the upstream with conversion to libnuke format
- opensearchservice-packages
- opensearchservice-vpcendpoints

 add new open search service resources from upstream converted to libnuke format

---

resources/cloudwatch-rum.go
resources/ec2-instance-connect-endpoint.go
resources/redshift-scheduled-action.go
tools/compare-resources/main.go

This adds the following resources from the upstream and converted to the libnuke format.
- redshift-scheduled-action
- ec2-instance-connect-endpoint
- cloudwatch-rum

add additional resources from upstream converted to libnuke format

---

resources/managedblockchain-member.go

This adds a new resource called `ManagedBlockchainMember`.

feat: add new resource ManagedBlockchainMember

---

.goreleaser.yml

Was missing the hook to actually sign the darwin binaries.

fix: missing hook to sign darwin binaries

---

docs/config-filtering.md
go.mod
go.sum

Updates to libnuke@0.10.0 which brings global filter support and adds documentation for it.

feat: global filters, update libnuke@0.10.0

---

.github/workflows/commit-lint.yaml

This adds commit-linting to all pull requests

ci: add commit lint workflow

---

resources/s3-buckets.go

Adds a log message when deleting s3 buckets that have over 500 objects, otherwise it appears that aws nuke just stalls out.

feat: write log message if s3 bucket deletion is going to take a while

---

resources/ec2-vpc-endpoint-service-configurations.go

ref: https://github.com/rebuy-de/aws-nuke/pull/1175

feat(EC2VPCEndpointServiceConfiguration): add tags to properties

---

resources/ec2-vpn-connections.go
resources/networkmanager-connect-peers.go
resources/networkmanager-core-network.go
resources/networkmanager-global-network.go
resources/networkmanager-network-attachments.go

Cherry picks https://github.com/1solomonwakhungu/aws-nuke/commit/fc1cc696a368295f418fce8eabe94a281fbae21b into this project and modifies to libnuke resource format.
ref: https://github.com/rebuy-de/aws-nuke/pull/1170

feat: delete core network manager resources

---

resources/sagemaker-domain.go
resources/sagemaker-domain_test.go

Fix a bug introduced by mocking the SageMakerDomain Lister
Resolves #110

fix(sagemaker-domain): bug with mock service vs real service

---

pkg/commands/nuke/nuke.go

This adds the missing option `--max-wait-retries`
Resolves #120

feat: add missing max-wait-retries

---

resources/cloudfront-cache-policy.go

A couple minor fixes related to the earlier #136 from issue #135

fix(cloudfront-cache-policy): add legacy stringer, add name property

---

resources/ec2-instance.go

PR for #138 with proper naming conventions and commit signing.

feat: remove EC2 instances tags before termination

---

resources/ec2-nat-gateways.go
resources/ec2-volume.go

Upstream PR https://github.com/rebuy-de/aws-nuke/pull/1222

fix: add CreateTime property to EC2NATGateway and EC2Volume resources

---

.github/workflows/goreleaser.yml

chore(deps): downgrade to goreleaser/goreleaser-action action to v5 [release skip]

---

.releaserc.yml

chore: remove beta channel

---

resources/kms-aliases.go

This adds pagination support to KMS Alias resource such that all aliases will be discovered and processed for removal.
Resolves #205 
A user opened a PR upstream, but it can't apply cleanly anymore, and there are a lot of extra files, so unfortunately I manually implemented the changes. https://github.com/rebuy-de/aws-nuke/pull/1113

feat(kms-alias): support pagination

---

resources/apigateway-restapis.go
resources/apigatewayv2-apis.go

adds the creation timestamp for apigateways

feat(apigateway): add created date to apigateways

---

resources/iam-user-access-key.go
resources/iam-user.go

* feat(iam): add createdate for iam users
* feat(iam): add createdate for access keys

feat(iam): add creation dates for iam users and iam access keys

---

resources/glue-blueprints.go
resources/glue-ml-transforms.go
resources/glue-sessions.go
resources/glue-workflows.go

Commits were cherry-picked from upstream contributor to keep attribution however to meet requirements for semantic commit messages, it was rebased and reworded accordingly. Additionally the resources were refactored for libnuke format and standards.
Upstream PR https://github.com/rebuy-de/aws-nuke/pull/1218

feat: adding resources for AWS Glue Blueprints, ML Transforms, Sessions, and Workflows

---

go.mod
go.sum
resources/kms-key_mock_test.go

fix: kms key tag missing

---

docs/installation.md

docs: fix brew install command

---

resources/iam-service-specific-credentials.go
resources/iam-user.go
resources/iam-user_mock_test.go

Adds several new properties to the `IAMUser` resource type.
Implements upstream https://github.com/rebuy-de/aws-nuke/pull/758

feat(iam-user): add new properties

---

go.mod
go.sum

fix(deps): update to libnuke@v0.19.1

---

resources/backup-report-plan.go

Added support to list and remove BackupReportPlans https://docs.aws.amazon.com/aws-backup/latest/devguide/API_DeleteReportPlan.html

feat: add support for backup-report-plan

---

resources/redshift-snapshot-schedule.go

Implements https://github.com/rebuy-de/aws-nuke/pull/1098
Takes the commit from @MikeSchouw and converts to libnuke format and rebases the commits to conventional commit syntax.

feat(resource): add redshift snapshot schedule

---

docs/quick-start.md
docs/starter-config.md
mkdocs.yml
resources/backup-vault.go
resources/ec2-default-security-group-rule.go
resources/gamelift-mm-config.go
resources/gamelift-mm-rule.go
resources/quicksight-subscriptions.go
resources/quicksight-user.go
resources/transcribe-call-analytics-category.go
resources/transcribe-call-analytics-job.go

- Fixes several resources to not through errors when in unsupported regions
- Fixes a missing property for ec2 default security group rules
- Adds documentation with a good starter configuration

feat: general improvements

---

resources/iam-user_test.go
resources/s3-bucket_test.go

Fixes integration tests for IAM and S3. To run integration tests you must build using tag `integration`

fix: tests

---

docs/config-filtering.md
docs/features/global-filters.md
docs/index.md

docs: add clarity around filter and filter examples

---

resources/bedrock-agent-datasource.go
resources/bedrock-agent-knowledge-base.go
resources/bedrock-agent-prompt.go
resources/bedrock-agent.go

feat(bedrockagent): add agent, prompt, datasource and knowledge base

---

resources/ec2-tgw.go
resources/ec2-tgw_test.go

fix(ec2-tgw): filter out gateways not owned by account

---

docs/resources/neptune-cluster.md
docs/resources/neptune-instance.md
docs/resources/sfn-state-machine.md
resources/neptune-cluster.go
resources/neptune-clusters.go
resources/neptune-instance.go
resources/rds-instances.go
resources/sfn-state-machine.go

- Resolves https://github.com/ekristen/aws-nuke/issues/415
- Resolves https://github.com/ekristen/aws-nuke/issues/306
- Resolves https://github.com/ekristen/aws-nuke/issues/403

feat: various feats and fixes

---

resources/cloudwatch-alarm.go
resources/cloudwatch-alarms.go

feat: support composite cloudwatch alarms

---

resources/ec2-tgw.go

fix(ec2-tgw): ensure state is set

---

resources/resource-explorer2-index.go
resources/resource-explorer2-indexes.go

- fixes #469 
- refactors to standardization
- adds properties support

feat: resource explorer2 index overhaul

---

resources/cognito-userpool.go
resources/cognito-userpool_mock_test.go

fix(cognito-userpool): include user attribute update settings

---

resources/neptune-cluster.go
resources/neptune-snapshot.go

- Adds new properties to neptune snapshot
- Refactors neptune snapshot to align with libnuke resource format, including having properties
- Filters cluster and snapshot to just neptune engine
- Resolves #486 
- Resolves #487

feat: neptune - new properties and fix filter on engine

---

docs/resources/ssm-quick-setup-configuration-manager.md
go.mod
go.sum
mkdocs.yml
pkg/commands/nuke/nuke.go
resources/ssmquicksetup-configuration-manager.go
tools/create-resource/main.go

This adds the SSM QuickSetup Configuration Manager resource as well as fixes a bug related to logging accidentally moving to stderr from stdout.
Resolves #491

feat: ssm quick setup resources

---

docs/resources/ec2-network-interface.md
docs/resources/route-53-hosted-zone.md
docs/resources/route-53-profile-association.md
docs/resources/route-53-profile.md
mkdocs.yml
resources/ec2-dhcp-option.go
resources/ec2-dhcp-option_test.go
resources/ec2-internet-gateway-attachment.go
resources/ec2-internet-gateway-attachment_test.go
resources/ec2-internet-gateway.go
resources/ec2-internet-gateway_test.go
resources/ec2-network-interface.go
resources/ec2-network-interface_test.go
resources/ec2-route-table.go
resources/ec2-route-table_test.go
resources/ec2-security-group.go
resources/ec2-security-group_test.go
resources/ec2-subnet.go
resources/ec2-subnet_test.go
resources/ec2-vpc.go
resources/ec2-vpc_helpers.go
resources/ec2-vpc_test.go

- Resolves #497 
- Resolves #528

feat: ec2 - filter out shared resources

---

resources/ec2-network-interface.go

fix(ec2-network-interfaces): set description property

---

resources/ecs-capacity-provider.go

fix(ecs-capacity-provider): check delete failure

---

go.mod
go.sum
resources/appsync-api-association.go
resources/appsync-domainnames.go

feat(appsync): support domain names

---

resources/ec2-internet-gateway-attachment.go

fix(ec2-internet-gateway-attachment): include account id properly

---

docs/cli-usage.md

`config-details` is now `explain-config`.

docs: fix old command

---

resources/apigateway-domain-name.go
resources/apigateway-domainnames.go

This PR adds tagging support for the APIGatewayDomainName resource in aws-nuke. The changes ensure that tags are properly fetched and displayed when listing resources, allowing for better filtering and exclusions during cleanup operations.

feat: add tag support for APIGatewayDomainName resource

---

resources/apigateway-domain-name.go

fix(apigateway-domain-name): error getting tags for private apis

---

resources/cloudwatchlogs-loggroup.go

This pull request fixes the following error:
```
ERRO[0258] listing failed:
ThrottlingException: Rate exceeded  error="ThrottlingException: Rate exceeded" owner=ap-southeast-2 resource_type=CloudWatchLogsLogGroup
```
aws-nuke was not rate-limiting `ListTagsForResource` and `DeleteLogGroup` calls because they were not listed in the [CloudWatch logs quotas](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) page. Viewing the quotas via the AWS CLI reveals that these APIs do have rate limits.
I've also increased the rate limit for `DescribeLogStreams`, which [increased a year ago](https://aws.amazon.com/about-aws/whats-new/2024/03/increased-default-quotas-cloudwatch-logs-apis/).

fix(cloudwatchlogs-loggroup): rate limits

---

resources/docdb-parametergroup.go

fix(docdb-parameter-group): filter default parameter group

---

.github/workflows/golangci-lint.yml
.github/workflows/tests.yml
go.mod
go.sum

This upgrades to libnuke@1.3.0 and fixes bug where if there are too many items scanned a deadlock occurs.

fix: deadlock

---

docs/resources/ec2-snapshot.md
docs/resources/ec2-volume.md
mkdocs.yml
resources/ec2-snapshots.go
resources/ec2-snapshots_test.go
resources/ec2-volume.go
resources/ec2-volume_test.go

- Refactor EBS volumes and snapshot to the new style.
- Add tests
- Add docs

feat: refactor EBS volumes and Snapshot and add tests
